package com.micro.web.dao;

import com.micro.web.pojo.UserInfo;

import java.util.Map;

import static org.apache.ibatis.jdbc.SqlBuilder.*;

public class UserInfoSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated
     */
    public String insertSelective(UserInfo record) {
        BEGIN();
        INSERT_INTO("user_info");
        
        if (record.getId() != null) {
            VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getName() != null) {
            VALUES("name", "#{name,jdbcType=VARCHAR}");
        }
        
        if (record.getPassword() != null) {
            VALUES("password", "#{password,jdbcType=VARCHAR}");
        }
        
        if (record.getEmaill() != null) {
            VALUES("emaill", "#{emaill,jdbcType=VARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated
     */
    public String updateByPrimaryKeySelective(UserInfo record) {
        BEGIN();
        UPDATE("user_info");
        
        if (record.getName() != null) {
            SET("name = #{name,jdbcType=VARCHAR}");
        }
        
        if (record.getPassword() != null) {
            SET("password = #{password,jdbcType=VARCHAR}");
        }
        
        if (record.getEmaill() != null) {
            SET("emaill = #{emaill,jdbcType=VARCHAR}");
        }
        
        WHERE("id = #{id,jdbcType=INTEGER}");
        
        return SQL();
    }

    public String selectUserInfo(Map<String,Object> params){

        String name = (String) params.get("name");
        String password = (String) params.get("password");
        BEGIN();

        SELECT("id,name,password,emaill");

        FROM("user_info");

        if(name != null){
            WHERE("name = #{name,jdbcType=VARCHAR}");
        }
        if(password != null){
            WHERE("password = #{password,jdbcType=VARCHAR}");
        }
        return SQL();
    }
}